---
  name: CI

  on:
    push:
      branches:
        - main
        - develop
        - beta
        # npm version tags
        - /^v\d+.\d+.\d+(?:-(?:alpha|beta|rc)\.\d+)?/
    pull_request:
  concurrency:
    group: ci-tests-${{ github.ref }}-1
    cancel-in-progress: true
  env:
    CI: true
    dist: ember-stereo/dist
  jobs:
    install_dependencies:
      name: Install Dependencies
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: ./.github/actions/pnpm
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      if: contains('refs/heads/main', github.ref) ||  contains('refs/heads/beta', github.ref)
      needs: []
      steps:
        - name: Dispatch Release
          uses: benc-uk/workflow-dispatch@v1
          with:
            workflow: Generate New Release
            token: ${{ secrets.GH_TOKEN }}
